server:
  port: 8821

spring:
  application:
    name: event_log_analyser
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:db/alertsdb;DB_CLOSE_DELAY=1000
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

app:
  log-analyser:
    alert-threshold-ms: 4
    table-rows-writeoff-count: 1000

